name: Secret Scanning
on: 
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Scan for secrets with TruffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          
      - name: Check for Supabase service role keys
        run: |
          echo "Checking for exposed Supabase service role keys..."
          
          # Pattern for service role keys (they start with eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9)
          if grep -r "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+" \
            --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
            --include="*.json" --include="*.env*" \
            --exclude-dir=node_modules --exclude-dir=.git \
            --exclude=".env.example" .; then
            echo "::error::🚨 Potential Supabase service role key found in code!"
            echo "::error::Service role keys should only be in environment variables"
            exit 1
          fi
          
      - name: Check for other sensitive patterns
        run: |
          echo "Checking for other sensitive patterns..."
          
          # Check for hardcoded API keys
          if grep -r "sk_live_\|pk_live_\|sk_test_\|pk_test_" \
            --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
            --exclude-dir=node_modules --exclude-dir=.git .; then
            echo "::warning::Potential Stripe key found - ensure it's in environment variables"
          fi
          
          # Check for database URLs with credentials
          if grep -r "postgresql://.*:.*@" \
            --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
            --exclude-dir=node_modules --exclude-dir=.git .; then
            echo "::error::Database URL with credentials found in code!"
            exit 1
          fi
          
          echo "✅ Secret scan completed successfully" 